# Install a test application to check configuration
- name: EXAMPLE01
  hosts: ansible-srv1
  become: true
  vars_files:
    - vars/example01.yml
  tasks:
    - name: Debug VARS
      debug:
        msg: "{{ ex01_host }}:{{ ex01_port }}"
    - name: Updates APT Cache
      apt:
        update_cache: yes
    - name: Install Python
      apt:
        name: [ "python3", "python3-pip", "python3-dev" ]
    - name: Install Python Libraries for Example 01
      pip:
        name: [ "flask==2.2.2"]
    - name: Copy Python Files
      copy:
        src:  code/example01/main.py
        dest: /opt/app/
    - name: Execute Python Application
      shell: cd /opt/app/ && nohup flask --no-debug --app main run --host "{{ ex01_host }}" --port "{{ ex01_port }}" &
