# Install a test application to check configuration
- name: EXAMPLE01_ERASE
  hosts: ansible-srv1
  become: true
  vars_files:
    - vars/example02.yml
  tasks:
    - name: Kill All Flask Processes
      shell: killall pyhon3
